version: 0.2


phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo build process started now
      - npm run start
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now