version: 0.2

proxy:
  upload-artifacts: yes

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - n 16
      - npm install --force
      - cd ./server && npm install --force
  build:
    commands:
      - echo build process started now
      - npm run build
      - cd ../ && npm run build
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now

artifacts:
  files:
    - '**/*'

  discard-paths: yes
  
  